# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-03-18 16:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Thing',
            new_name='Profile',
        ),
    ]
